{'issues': [{'swcID': 'SWC-110', 'swcTitle': 'Assert Violation', 'description': {'head': 'A reachable exception has been detected.', 'tail': 'It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.'}, 'severity': 'Low', 'locations': [{'sourceMap': '156:1:1'}], 'extra': {'testCase': {'initialState': {'accounts': None}, 'steps': None}}}], 'sourceType': 'raw-bytecode', 'sourceFormat': 'evm-byzantium-bytecode', 'sourceList': ['0xaab670b3d565e9ca7e3ea219e0813d8e14aeb9418a1e754b05cff750ef3c65ad', '0x5cc81c40771d80a035f426db66f12e4a0fb48b008bc27f45c0ceb75e94dc7b73'], 'meta': {'coveredInstructions': 108, 'coveredPaths': 6}}
